/*
 * This file is generated by jOOQ.
 */
package com.sm.jooq.tables.pojos;


import com.sm.jooq.tables.interfaces.IOrders;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements IOrders {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   productId;
    private String description;

    public Orders() {}

    public Orders(IOrders value) {
        this.id = value.getId();
        this.productId = value.getProductId();
        this.description = value.getDescription();
    }

    public Orders(
        Long   id,
        Long   productId,
        String description
    ) {
        this.id = id;
        this.productId = productId;
        this.description = description;
    }

    /**
     * Getter for <code>product_management.orders.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>product_management.orders.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>product_management.orders.product_id</code>.
     */
    @Override
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>product_management.orders.product_id</code>.
     */
    @Override
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>product_management.orders.description</code>.
     */
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>product_management.orders.description</code>.
     */
    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IOrders from) {
        setId(from.getId());
        setProductId(from.getProductId());
        setDescription(from.getDescription());
    }

    @Override
    public <E extends IOrders> E into(E into) {
        into.from(this);
        return into;
    }
}
