/*
 * This file is generated by jOOQ.
 */
package com.sm.jooq.tables.pojos;


import com.sm.jooq.tables.interfaces.IProducts;

import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Products implements IProducts {

    private static final long serialVersionUID = 1L;

    private Long       id;
    private String     description;
    private String     name;
    private BigDecimal price;

    public Products() {}

    public Products(IProducts value) {
        this.id = value.getId();
        this.description = value.getDescription();
        this.name = value.getName();
        this.price = value.getPrice();
    }

    public Products(
        Long       id,
        String     description,
        String     name,
        BigDecimal price
    ) {
        this.id = id;
        this.description = description;
        this.name = name;
        this.price = price;
    }

    /**
     * Getter for <code>product_management.products.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>product_management.products.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>product_management.products.description</code>.
     */
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>product_management.products.description</code>.
     */
    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>product_management.products.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>product_management.products.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>product_management.products.price</code>.
     */
    @Override
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>product_management.products.price</code>.
     */
    @Override
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Products (");

        sb.append(id);
        sb.append(", ").append(description);
        sb.append(", ").append(name);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IProducts from) {
        setId(from.getId());
        setDescription(from.getDescription());
        setName(from.getName());
        setPrice(from.getPrice());
    }

    @Override
    public <E extends IProducts> E into(E into) {
        into.from(this);
        return into;
    }
}
