/*
 * This file is generated by jOOQ.
 */
package com.sm.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IOrders extends Serializable {

    /**
     * Setter for <code>product_management.orders.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>product_management.orders.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>product_management.orders.product_id</code>.
     */
    public void setProductId(Long value);

    /**
     * Getter for <code>product_management.orders.product_id</code>.
     */
    public Long getProductId();

    /**
     * Setter for <code>product_management.orders.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>product_management.orders.description</code>.
     */
    public String getDescription();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IOrders
     */
    public void from(IOrders from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IOrders
     */
    public <E extends IOrders> E into(E into);
}
