/*
 * This file is generated by jOOQ.
 */
package com.sm.jooq.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProducts extends Serializable {

    /**
     * Setter for <code>product_management.products.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>product_management.products.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>product_management.products.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>product_management.products.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>product_management.products.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>product_management.products.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>product_management.products.price</code>.
     */
    public void setPrice(BigDecimal value);

    /**
     * Getter for <code>product_management.products.price</code>.
     */
    public BigDecimal getPrice();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IProducts
     */
    public void from(IProducts from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IProducts
     */
    public <E extends IProducts> E into(E into);
}
