/*
 * This file is generated by jOOQ.
 */
package com.sm.jooq;


import com.sm.jooq.tables.Orders;
import com.sm.jooq.tables.Products;


/**
 * Convenience access to all tables in product_management.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>product_management.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>product_management.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;
}
